<?xml version="1.0"?>
<package format="2">
  <name>hpipm-cpp</name>
  <version>0.0.0</version>
  <description>C++ wrapper for HPIPM</description>

  <maintainer email="sugihara@jsk.imi.i.u-tokyo.ac.jp">Kazuki Sugihara</maintainer>
  <license>MIT</license>

  <buildtool_depend>cmake</buildtool_depend>

  <build_depend>blasfeo</build_depend>
  <build_depend>hpipm</build_depend>
  <build_depend>eigen</build_depend>

  <build_export_depend>blasfeo</build_export_depend>
  <build_export_depend>hpipm</build_export_depend>
  <build_export_depend>eigen</build_export_depend>

  <exec_depend>blasfeo</exec_depend>
  <exec_depend>hpipm</exec_depend>
  <exec_depend>eigen</exec_depend>

  <export>
    <build_type>cmake</build_type>
  </export>

</package>
